version: '3.8'

networks:
  services_network:
    driver: bridge
    
services:
  nats:
    image: docker.io/library/nats:2.12.0-alpine
    volumes:
      - ./docker/docker-data/nats-store:/nats/jetstream
      - ./docker/docker-data/nats-log:/nats/logs/
      - ./docker/nats/nats-server.conf:/etc/nats/nats-server.conf
      - ./docker/nats/certs:/certs
    command: "--config /etc/nats/nats-server.conf &"
    networks:
      - services_network
    ports:
      - "4222:4222"
      - "8080:8080"
    restart: on-failure
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--spider",
          "http://localhost:8222/healthz"
        ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s
