# Client port of 4222 on all interfaces
port: 4222
# HTTP monitoring port
monitor_port: 8222

# Logging
debug: true
trace: true
logtime: false
logfile_size_limit: 1GB
logfile_max_num: 100
log_file: "/tmp/nats-server.log"

# Set maximum message size
max_payload: 8M


# Setup TLS required for the WebSocket
tls {
    cert_file: "/certs/server.pem"
    key_file: "/certs/server-key.pem"
    ca_file: "/certs/ca.pem" # Optional, only needed for Mutual TLS
}

# JetStream
jetstream {
  store_dir: "/nats/jetstream"
  max_mem: 4G
  max_file: 10G
}

# Define the WebSocket Block
websocket {
  port: 8080
  no_tls: true
}

# Accounts
accounts {
  app: {
    jetstream: enabled
    users: [
      {
        user: user
        password: password 
        permissions: {
          publish: ">"
          subscribe: ">"
        }
      }
    ]
  }
}

# Logging
log_file: "/nats/logs/nats.log"